modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/camera/issues"
[[mods]]
modId = "camera"
version = "${mod_version}"
displayName = "Camera Mod"
updateJSONURL = "https://update.maxhenkel.de/neoforge/camera"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/camera-mod"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''This mod adds a working camera'''
[[mixins]]
config = "camera.mixins.json"
[[dependencies.camera]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.camera]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.camera]]
modId = "jei"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.camera]]
modId = "jade"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"